home/urls.py
from django.urls import path, include
from home import views
from report.views import list_all_patients_view


app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('add-user/', views.addUserView, name='new-user'),
        path('register/', views.register, name='register'),
        path('', views.homepage, name='homepage'),
        path('', list_all_patients_view, name='rep-all-patients'),
]

patient/urls.py
from django.urls import path
from patient import views

app_name = 'patient'

urlpatterns =[
    path('patient/list/', views.list_patients_view, name='all-patients'),
    path('patient/create/', views.create_patient_view, name='create-patient'),
    path('patient/view/<int:pk>', views.view_patient_view, name='view-patient'),
    path('patient/update/<int:pk>', views.update_patient_view, name='update-patient'),
    path('patient/delete/<int:pk>', views.delete_patient, name='delete-patient'),
    path('gyno/list/', views.list_gyno_view, name='all-gynos'),
    path('gyno/create/', views.create_gyno_view, name='create-gyno'),
    path('gyno/update/<int:pk>', views.update_gyno_view, name='update-gyno'),
    path('gyno/delete/<int:pk>', views.delete_gyno_view, name='delete-gyno'),
    path('delivery/create/list/<int:pk>', views.create_delivery_view, name='all-delivery'),
    path('delivery/update/list/<int:pk>/<int:patient_id>', views.update_delivery_view, name='update-delivery'),
    path('checkup/create/list/<int:patient_id>', views.create_list_check_up_view, name='all-checkup'),
    path('us/create/<int:check_id>/<int:patient_id>/', views.ultrasound_create_view, name='create-us'),
    path('checkup/view/<int:patient_id>/<int:chk_id>', views.view_list_check_up_view, name='view-checkup'),
    path('checkup/update/<int:patient_id>/<int:chk_id>', views.update_patient_medicine_view, name='update-checkup'),
    path('medicine/create/<int:patient_id>/<int:chk_id>', views.create_patient_medicine_view, name='create-med'),
    path('cons/list/', views.list_patient_consultant_view, name='all-con-patients'),
    path('create/days-off/<int:patient_id>', views.create_patient_days_off_view, name='create-days-off'),
    path('create/diabete/<int:patient_id>', views.create_diabetes_view, name='create-diabetes'),
    path('chart/diabete/<int:patient_id>', views.patient_diabete_chart, name='patients-diabetes-chart'),


    path('search/barcode/', views.view_patient_barcode, name='search-barcode'),
]

pharmacy/urls.py
from django.urls import path
from pharmacy import views

app_name = 'pharmacy'

urlpatterns =[
    path('list/', views.list_medicines_view, name='all-medicines'),
    path('medicine/create/', views.create_medicine_view, name='create-medicine'),
    path('medicine/update/<int:pk>', views.update_medicine_view, name='update-medicine'),
     path('medicine/delete/<int:pk>', views.delete_medicine_view, name='delete-medicine'),
]

report/urls.py
from django.urls import path
from report import views

app_name = 'report'

urlpatterns =[
          path('patient/api/', views.report_dashboard_view, name='rep-dashboard'),
          path('patient/details/api/', views.total_patients_details_view, name='total-patients-details'),
          path('all/patients/report/', views.list_all_patients_view, name='rep-all-patients'),
          path('cons/patients/report/', views.list_consultant_patients_view, name='rep-cons-patients'),
          path('clexane/patients/report/', views.list_clexane_patients_view, name='rep-clexane-patients'),
          path('view/patient/report/<int:patient_id>', views.view_patient_history_view, name='patient-report'),
          path('view/patient/checkup/<int:checkup_id>', views.patient_checkup_report_view, name='patient_check_up_report'),
          path('patients/entrance/chart/', views.patients_entrance_chart, name='patients-entrance-chart'),
          path('delivery/type/chart/', views.delivery_type_chart, name='delivery-type-chart'),
          path('surgery/type/chart/', views.surgery_type_chart, name='surgery-type-chart'),
]

surgery/urls.py
from django.urls import path
from surgery import views

app_name = 'surgery'

urlpatterns =[
              path('list/', views.list_surgery_view, name='list-surgery-types'),
              path('create/', views.create_surgery_view, name='create-surgery'),
              path('update/<int:pk>', views.update_surgery_view, name='update-surgery'),
              path('view/<int:pk>', views.view_surgery_view, name='view-surgery'),
              path('delete/<int:pk>', views.delete_surgery_view, name='delete-surgery'),
              path('create/patient/surgery/<int:patient_id>', views.create_patient_surgery_view, name='create-patient-surgery'),
              path('list/doctors/', views.list_surgery_doctor_view, name='list-surgery-doctors'),
              path('create/doctor/', views.create_surgery_doctor_view, name='create-doctor'),
              path('update/doctor/<int:pk>', views.update_surgery_doctor_view, name='update-doctor'),
              path('delete/doctor/<int:pk>', views.delete_surgery_doctor_view, name='delete-doctor'),
]

womanClinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
            path('i18n/', include('django.conf.urls.i18n')),
            path('admin/', admin.site.urls),
            path('', include('home.urls'), name='home'),
            path('patients/', include('patient.urls'), name='patient'),
            path('medicine/', include('pharmacy.urls'), name='pharmacy'),
            path('surgery/', include('surgery.urls'), name='surgery'),
            path('report/', include('report.urls'), name='reports'),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#             path('admin/', admin.site.urls),
#             path('', include('home.urls'), name='home'),
#             path('patients/', include('patient.urls'), name='patient'),
#             path('medicine/', include('pharmacy.urls'), name='pharmacy'),
#             path('surgery/', include('surgery.urls'), name='surgery'),
#             path('report/', include('report.urls'), name='reports'),
# )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

womanClinic/templates/add-user.html
{% extends 'master.html' %}
{% load static%}
{% load i18n %}
{% load l10n %}
{% load crispy_forms_tags %}

{% block body %}
<form method="post" id="my_form">
  {% csrf_token %}
  {% include 'message.html' %}
  <section class="panel panel-default">
    <div class="panel-body">
      <header class="panel-heading font-bold pull-right">{{page_title|title}}</header>
      <div class="doc-buttons pull-left">
        <a href="javascript:{}" onclick="document.getElementById('my_form').submit(); return false;" class="btn btn-s-md btn-primary ">{% trans "حفظ" %}</a>
      </div>
    </div>
  </section>
  <section class="panel panel-default">
    <div class="panel-body">
      <div class="form-group pull-in clearfix">
        <div class="pull-right">

        </div>
        <div class="col-sm-6 pull-right">
          {% for field in add_user %}
          <p>
            {{ field.label_tag }}<br>
            {{ field|as_crispy_field }}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</form>
{% endblock body %}

womanClinic/templates/footer.html
{% load static %}

<div class="text-center padder">
  <div class="row">
    <div class="col-md-12">
      <p>
        PixlStamp<br>Services & More &copy;
        <script type="text/javascript">
          document.write(new Date().getFullYear());
        </script> | All Rights Reserved</p>
    </div>
  </div>
</div>

womanClinic/templates/forgot-password.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" dir={% if LANGUAGE_BIDI%}"rtl" {%else%}"ltr"{%endif%}>

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Forgot Password</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                  </div>
                  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                      Reset Password
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="login.html">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

womanClinic/templates/language-switcher.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}

<form class="top-nav-search collapse pull-left" action="{% url 'set_language' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ redirect_to }}">
  <select class="form-control" name="language" onchange="this.form.submit()">
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    {% for lang in languages %}
    <option class="menu" value="{{ lang.code }}" {% if lang.code == LANGUAGE_CODE %} selected {% endif %}>
      {{ lang.name_local }} {{ lang.code }}
    </option>
    {% endfor %}
  </select>
</form>

womanClinic/templates/message.html
{% load static %}


{% for message in messages %}
  <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-header">
      <strong class="mr-auto">
        {% if message.tags == 'error' %}
          <i class="fas fa-times mr-2"></i>
        {% elif message.tags == 'warning' %}
          <i class="fas fa-exclamation mr-2"></i>
        {% elif message.tags == 'info' %}
          <i class="fas fa-info mr-2"></i>
        {% elif message.tags == 'success' %}
          <i class="fas fa-check mr-2"></i>
        {% endif %}
        {{message.tags|capfirst}}
      </strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      {{message|safe}}
    </div>
  </div>
{% endfor %}

womanClinic/templates/register.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE }}" dir={% if LANGUAGE_BIDI%}"rtl" {%else%}"ltr"{%endif%}  class="bg-dark">

<head>
  <meta charset="utf-8" />
  <link rel="shortcut icon" type="image/ico" href="{% static 'img/favicon.ico' %}" />
  <title>PeopleM8 {% trans "Login" %}</title>
  <meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <link rel="stylesheet" href="{% static 'css/font.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'js/calendar/bootstrap_calendar.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/app.v2.css' %}" type="text/css" />
</head>

<body class="bg-dark" style={% if LANGUAGE_CODE == 'ar' %} "text-align:right;" {% else %} "text-align:left;" {% endif %}>

  <section id="content" class="m-t-lg wrapper-md animated fadeInDown">
    <div class="container aside-xxl">
      <section class="panel panel-default bg-white m-t-lg">
        <header class="panel-heading text-center">
          <strong>{% trans "Sgin Up" %}</strong>
        </header>
        <form method="post" class="panel-body wrapper-lg">
          {% csrf_token %}
          <div class="illustration" align="center">
            <img style="max-height:120%;max-width: 100%;" src="{% static 'img/Peoplem83.png' %}">
          </div>
          {% for field in register_form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
          {% endfor %}
          <div class="checkbox">
            <label>
              <input type="checkbox">{% trans "Agree the" %}<a href="#">{% trans "terms and policy" %}</a>
            </label>
          </div>
          <button type="submit" class="btn btn-primary">{% trans "Sgin Up" %}</button>
          <div class="line line-dashed"></div>
          <p class="text-muted text-center">
            <small>Already have an account?</small></p>
          <a href="{% url 'home:user-login'%}" class="btn btn-default btn-block">{% trans "Sgin In" %}</a>
        </form>
      </section>
    </div>
  </section>
  <!-- footer -->
  <footer id="footer">
     {% include 'footer.html' %}
   </footer>
  <script src="{% static  'js/app.v2.js'%}"></script>
</body>

</html>

womanClinic/templates/side-bar.html
{% load static %}
{% load i18n %}
{% load l10n %}

<ul class="nav navbar-nav side-nav nicescroll-bar">
  <li class="navigation-header">
    <span>{% trans 'Main'%}</span>
    <i class="zmdi zmdi-more"></i>
  </li>
  <li>
    <a href="{% url 'report:rep-dashboard' %}">
      <div class="pull-left"><i class="zmdi zmdi-landscape mr-20"></i><span class="right-nav-text">{% trans 'Dashboard'%}</span></div>
      <div class="clearfix"></div>
    </a>
  </li>



  <li>
    <hr class="light-grey-hr mb-10" />
  </li>

  <li class="navigation-header">
    <span>{% trans 'Setup & main Pages'%}</span>
    <i class="zmdi zmdi-more"></i>
  </li>
  <li>
    <a href="javascript:void(0);" data-toggle="collapse" data-target="#ui_dr">
      <div class="pull-left"><i class="zmdi zmdi-smartphone-setup mr-20"></i><span class="right-nav-text">{% trans 'Setup & main Pages'%}</span></div>
      <div class="pull-right"><i class="zmdi zmdi-caret-down"></i></div>
      <div class="clearfix"></div>
    </a>
    <ul id="ui_dr" class="collapse collapse-level-1 two-col-list">
      <li>
        <a href="{% url 'patient:all-patients'%}">{% trans 'Patients' %}</a>
      </li>
      <li>
        <a href="{% url 'pharmacy:all-medicines'%}">{% trans 'Medicines' %}</a>
      </li>
      <li>
        <a href="{% url 'patient:all-gynos'%}">{% trans 'GYNOS Dygnosis' %}</a>
      </li>
      <li>
        <a href="{% url 'surgery:list-surgery-types'%}">{% trans 'Surgeries' %}</a>
      </li>
      <li>
        <a href="{% url 'surgery:list-surgery-doctors'%}">{% trans 'Surgery Doctors' %}</a>
      </li>
    </ul>
  </li>


  <li class="navigation-header">
    <span>{% trans 'Follow Up' %}</span>
    <i class="zmdi zmdi-more"></i>
  </li>

  <li>
    <a href="javascript:void(0);" data-toggle="collapse" data-target="#follow_up">
      <div class="pull-left"><i class="zmdi zmdi-smartphone-setup mr-20"></i><span class="right-nav-text">{% trans 'Follow Up' %}</span></div>
      <div class="pull-right"><i class="zmdi zmdi-caret-down"></i></div>
      <div class="clearfix"></div>
    </a>
    <ul id="follow_up" class="collapse collapse-level-1 two-col-list">
      <li>
        <a href="{% url 'patient:all-patients'%}">{% trans 'General Follow Up' %}</a>
      </li>
      <li>
        <a href="{% url 'patient:all-con-patients'%}">{% trans 'Consultant Follow Up' %}</a>
      </li>
    </ul>
  </li>



  <li>
    <a href="{% url 'report:rep-dashboard' %}">
      <div class="pull-left"><i class="zmdi zmdi-edit mr-20"></i><span class="right-nav-text">{% trans 'Reports'%}</span></div>
      <div class="clearfix"></div>
    </a>
  </li>

  <li>
    <hr class="light-grey-hr mb-10" />
  </li>
</ul>

womanClinic/templates/side_nav.html
{% load i18n %}
{% load l10n %}
{% load static %}
<div class="sidebar" role="navigation">
<div class="sidebar-nav collapse navbar-collapse show" id="side-menu-wrapper">
  <ul class="nav navbar-nav navbar-collapse flex-column side-nav list-group" id="side-menu">
    <li class="list-group-item">
      <a href="{% url 'report:rep-all-patients'%}">
        <i class="fa fa-dashboard fa-fw"></i>{% trans 'الرئيسية'%}</a>
    </li>
    <!-- بيانات اساسية -->
    <li class="list-group-item">
      <a href="#">
        <i class="fa fa-bar-chart-o fa-fw"></i>بيانات اساسية<span class="fa arrow">
        </span>
      </a>
      <ul class="nav-second-level list-group nested">
        <li class="list-group-item">
          <a href="{% url 'patient:create-patient'%}">تسجيل بيانات المرضي</a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'pharmacy:all-medicines'%}">تسجيل الادوية</a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'patient:all-gynos'%}">تشخيص امراض النسا</a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'surgery:list-surgery-types'%}">بيانات عمليات النسا</a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'surgery:list-surgery-doctors'%}">قاعدة بيانات الجراحين</a>
        </li>
      </ul>
      <!-- /.nav-second-level -->
    </li>
    <!-- نهاية بيانات اساسية -->
    <!-- شاشة المتابعات -->
    <li class="list-group-item">
      <a href="#">
        <i class="fa fa-wrench fa-fw">
        </i> المتابعات<span class="fa arrow"></span>
      </a>
      <ul class="nav-second-level list-group nested">
        <li class="list-group-item">
          <a href="{% url 'patient:all-patients'%}">متابعة عامة</a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'patient:all-con-patients'%}">متابعة الاستشاري</a>
        </li>
      </ul>
      <!-- /.nav-second-level -->
    </li>
    <!-- نهاية المتابعات -->
    <!-- شاشات التقارير -->
    <li class="list-group-item">
      <a href="#">
        <i class="fa fa-wrench fa-fw">
        </i>التقارير<span class="fa arrow"></span>
      </a>
      <ul class="nav-second-level list-group nested">
        <li class="list-group-item">
          <a href="{% url 'report:rep-dashboard' %}">تقارير</a>
        </li>
      </ul>
      <!-- /.nav-second-level -->
    </li>
    <!-- نهاية التقارير -->
  </ul>
</div>
</div>

womanClinic/templates/top-bar.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="mobile-only-brand pull-left">
    <div class="nav-header pull-left">
      <div class="logo-wrap">
        <a href="{% url 'home:rep-all-patients'%}">
          <span class="brand-text" style="font-size: medium;">{% trans 'Toson Hospital' %}</span>
        </a>
      </div>
    </div>
    <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);">
      <i class="zmdi zmdi-menu"></i></a>
    <a id="toggle_mobile_search" data-toggle="collapse" data-target="#search_form" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-search"></i></a>
    <a id="toggle_mobile_nav" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-more"></i></a>
  </div>
  {% include 'language-switcher.html' %}

  <div id="mobile_only_nav" class="mobile-only-nav pull-right">
    <ul class="nav navbar-right top-nav pull-right">
      <li class="dropdown auth-drp">
        <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown">
          <span class="brand-text">{% trans 'WELCOME ' %} &ensp; {{request.user.first_name}} {{request.user.last_name}}</span>
        </a>

        <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
          <li class="divider"></li>
          <li>
            <a href="{% url 'home:logout' %}"><i class="zmdi zmdi-power"></i><span>{% trans 'LOG OUT' %}</span></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

womanClinic/templates/top_nav.html
{% load i18n %}
{% load l10n %}
{% load static %}

<div class="align-items-baseline d-flex flex-row navbar-brand p-lg-3 pl-3 pr-3 pt-3">
  <img style="max-height:50px;max-width: 100px;" src="{% static 'img/gyn.png' %}"></a>
  <button class="collapsed ml-auto navbar-toggler" type="button" data-toggle="collapse" data-target="#side-menu-wrapper" aria-controls="side-menu" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
<ul class="nav navbar-nav mr-md-auto flex-row navbar-top-links">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      <span class="profile-ava">
        {% trans 'مرحبا' %} &emsp;
      </span>
      <span class="username">{{request.user.first_name}} &ensp; {{{{request.user.last_name}}}}</span>
    </a>
    <div class="dropdown-menu dropdown-menu-right dropdown-user">
      <a class="dropdown-item" href="{% url 'home:new-user'%}">
        {% if user.is_superuser %}
        <i class="fa fa-user fa-fw"></i>{% trans "ADD NEW USER" %}</a>
        {% endif %}
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal" href="#"><i class="fa fa-sign-out fa-fw"></i>{% trans "LOG OUT" %}</a>
    </div>
  </li>
</ul>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans "واثق من الخروج؟" %}</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body">{% trans "اذا اردت الخروج من البرنامج اضغط خروج" %}</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">{% trans "Cancel" %}</button>
        <a class="btn btn-info" href="{% url 'home:logout'%}">{% trans "خروج" %}</a>
      </div>
    </div>
  </div>
</div>