home/urls.py
from django.urls import path, include
from home import views
from report.views import list_all_patients_view


app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('add-user/', views.addUserView, name='new-user'),
        path('register/', views.register, name='register'),
        path('', views.homepage, name='homepage'),
        path('', list_all_patients_view, name='rep-all-patients'),
]

patient/urls.py
from django.urls import path
from patient import views

app_name = 'patient'

urlpatterns =[
    path('patient/list/', views.list_patients_view, name='all-patients'),
    path('patient/create/', views.create_patient_view, name='create-patient'),
    path('patient/view/<int:pk>', views.view_patient_view, name='view-patient'),
    path('patient/update/<int:pk>', views.update_patient_view, name='update-patient'),
    path('patient/delete/<int:pk>', views.delete_patient, name='delete-patient'),
    path('gyno/list/', views.list_gyno_view, name='all-gynos'),
    path('gyno/create/', views.create_gyno_view, name='create-gyno'),
    path('gyno/update/<int:pk>', views.update_gyno_view, name='update-gyno'),
    path('gyno/delete/<int:pk>', views.delete_gyno_view, name='delete-gyno'),
    path('delivery/create/list/<int:pk>', views.create_delivery_view, name='all-delivery'),
    path('delivery/update/list/<int:pk>/<int:patient_id>', views.update_delivery_view, name='update-delivery'),
    path('checkup/create/list/<int:patient_id>', views.create_list_check_up_view, name='all-checkup'),
    path('us/create/<int:check_id>/<int:patient_id>/', views.ultrasound_create_view, name='create-us'),
    path('checkup/view/<int:patient_id>/<int:chk_id>', views.view_list_check_up_view, name='view-checkup'),
    path('checkup/update/<int:patient_id>/<int:chk_id>', views.update_patient_medicine_view, name='update-checkup'),
    path('medicine/create/<int:patient_id>/<int:chk_id>', views.create_patient_medicine_view, name='create-med'),
    path('cons/list/', views.list_patient_consultant_view, name='all-con-patients'),
    path('create/days-off/<int:patient_id>', views.create_patient_days_off_view, name='create-days-off'),
    path('create/diabete/<int:patient_id>', views.create_diabetes_view, name='create-diabetes'),
    path('chart/diabete/<int:patient_id>', views.patient_diabete_chart, name='patients-diabetes-chart'),


    path('search/barcode/', views.view_patient_barcode, name='search-barcode'),
]

surgery/urls.py
from django.urls import path
from surgery import views

app_name = 'surgery'

urlpatterns =[
              path('list/', views.list_surgery_view, name='list-surgery-types'),
              path('create/', views.create_surgery_view, name='create-surgery'),
              path('update/<int:pk>', views.update_surgery_view, name='update-surgery'),
              path('view/<int:pk>', views.view_surgery_view, name='view-surgery'),
              path('delete/<int:pk>', views.delete_surgery_view, name='delete-surgery'),
              path('create/patient/surgery/<int:patient_id>', views.create_patient_surgery_view, name='create-patient-surgery'),
              path('list/doctors/', views.list_surgery_doctor_view, name='list-surgery-doctors'),
              path('create/doctor/', views.create_surgery_doctor_view, name='create-doctor'),
              path('update/doctor/<int:pk>', views.update_surgery_doctor_view, name='update-doctor'),
              path('delete/doctor/<int:pk>', views.delete_surgery_doctor_view, name='delete-doctor'),
]

womanClinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
            path('i18n/', include('django.conf.urls.i18n')),
            path('admin/', admin.site.urls),
            path('', include('home.urls'), name='home'),
            path('patients/', include('patient.urls'), name='patient'),
            path('medicine/', include('pharmacy.urls'), name='pharmacy'),
            path('surgery/', include('surgery.urls'), name='surgery'),
            path('report/', include('report.urls'), name='reports'),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#             path('admin/', admin.site.urls),
#             path('', include('home.urls'), name='home'),
#             path('patients/', include('patient.urls'), name='patient'),
#             path('medicine/', include('pharmacy.urls'), name='pharmacy'),
#             path('surgery/', include('surgery.urls'), name='surgery'),
#             path('report/', include('report.urls'), name='reports'),
# )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/views.py
import os
from django.conf import settings
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.contrib.auth.decorators import login_required
from datetime import date
from django.http import JsonResponse, HttpResponse, Http404
from django.contrib import messages
from patient.models import (Patient, Patient_Files, Delivery, Check_Up,
                            Gynecology, Patient_Medicine, Patient_Days_Off,
                            Ultrasound, Diabetes, Patient_Exit, Past_Medical_History)
from patient.forms import (PatientForm, Patient_Files_formset,
                           DeliveryForm, Delivery_Check_Up_formset,
                           Gynecology_formset, GynecologyForm,
                           Check_Up_Form, Patient_Medicine_formset,
                           Patient_Days_Off_formset, Ultrasound_Form,
                           Diabetes_Form, Patient_Exit_Form, Past_Medical_History_Form)
from django.utils.translation import ugettext_lazy as _


@login_required(login_url='/login')
def list_patients_view(request):
    all_patients = Patient.objects.all()
    return render(request, 'list-patients.html', context={'page_title':_('All Patients'),'all_patients':all_patients})

@login_required(login_url='/login')
def create_patient_view(request):
    patient_form = PatientForm(form_type='create',)
    patient_attachments = Patient_Files_formset()
    patient_past_med = Past_Medical_History_Form(form_type='create',)
    if request.method == 'POST':
        patient_form = PatientForm(request.POST, form_type='create')
        patient_attachments = Patient_Files_formset(request.POST, request.FILES)
        patient_past_med = Past_Medical_History_Form(request.POST, form_type='create')
        if patient_form.is_valid() and patient_attachments.is_valid() and patient_past_med.is_valid():
            master_obj = patient_form.save(commit=False)
            master_obj.hospital_id = request.user.clinic_id
            master_obj.barcode = master_obj.insurance_number
            master_obj.created_by = request.user
            master_obj.last_update_by = request.user
            master_obj.save()
            patient_attachments = Patient_Files_formset(request.POST, request.FILES, instance=master_obj)
            detail_obj = patient_attachments.save(commit=False)
            for x in detail_obj:
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
            past_med_obj = patient_past_med.save(commit=False)
            past_med_obj.patient = master_obj
            past_med_obj.created_by = request.user
            past_med_obj.last_update_by = request.user
            past_med_obj.save()
            if master_obj.patient_type == 'DELIVER' :
                messages.success(request, 'تم الحفظ بنجاح')
                return redirect('patient:all-delivery', pk=master_obj.id)
            elif master_obj.patient_type == 'OPERATION'  :
                messages.success(request, 'تم الحفظ بنجاح')
                return redirect('surgery:create-patient-surgery', patient_id=master_obj.id)
            else :
                messages.success(request, 'تم الحفظ بنجاح')
                return redirect('patient:all-checkup', patient_id=master_obj.id)
        else:
            if patient_form.errors:
                messages.error(request, patient_form.errors)
            elif patient_attachments.errors:
                for error in patient_attachments.errors:
                    messages.error(request, error)
            elif patient_past_med.errors:
                messages.error(request, patient_past_med.errors)
    createContext = {
                     'page_title':_('ADD NEW PATIENT'),
                     'patient_form':patient_form,
                     'patient_attachments':patient_attachments,
                     'patient_past_med':patient_past_med,
    }
    return render(request, 'create-patient.html', createContext)

@login_required(login_url='/login')
def view_patient_view(request, pk):
    required_patient = get_object_or_404(Patient, pk=pk)
    patient_form = PatientForm(form_type='view', instance=required_patient)
    patient_attachments = Patient_Files.objects.filter(patient = pk)
    required_patient_past_med = Past_Medical_History.objects.filter(patient = pk).first()
    patient_past_med = Past_Medical_History_Form(form_type='view', instance=required_patient_past_med)
    # patient_attachments = Patient_Files_formset(instance=required_patient)
    exit_form = Patient_Exit_Form()
    if request.method == 'POST':
        exit_form = Patient_Exit_Form(request.POST)
        if exit_form.is_valid():
            exit_obj = exit_form.save(commit=False)
            exit_obj.patient = required_patient
            exit_obj.created_by = request.user
            exit_obj.last_update_by = request.user
            exit_obj.save()
            return redirect('patient:view-patient', pk=pk)
    createContext = {
                     'page_title':_('FOLLOW UP MAIN PAGE'),
                     'patient_id':pk,
                     'patient_form':patient_form,
                     'patient_attachments':patient_attachments,
                     'patient_past_med':patient_past_med,
                     'media_url':settings.MEDIA_URL,
                     'exit_form':exit_form,
                     'required_patient':required_patient
    }
    return render(request, 'view-patient.html', createContext)


@login_required(login_url='/login')
def view_patient_barcode(request):
    if request.method == "POST":
        url_code = request.POST.get('barcode')
        truncated_barcode = url_code[:-1]
        try:
            required_patient = get_object_or_404(Patient, barcode=truncated_barcode)
            return redirect('patient:view-patient', pk= required_patient.pk)
        except Http404:
            raise


@login_required(login_url='/login')
def update_patient_view(request, pk):
    required_patient = Patient.objects.get(pk=pk)
    patient_form = PatientForm(form_type='update', instance=required_patient)
    required_patient_past_med = Past_Medical_History.objects.filter(patient = pk).first()
    patient_past_med = Past_Medical_History_Form(form_type='update', instance=required_patient_past_med)
    patient_attachments = Patient_Files_formset(instance=required_patient)
    if request.method == 'POST':
        patient_form = PatientForm(request.POST, form_type='update', instance=required_patient)
        patient_past_med = Past_Medical_History_Form(request.POST, form_type='update', instance=required_patient)
        patient_attachments = Patient_Files_formset(request.POST, request.FILES, instance=required_patient)
        if patient_form.is_valid() and patient_attachments.is_valid() and patient_past_med.is_valid():
            master_obj = patient_form.save(commit=False)
            master_obj.created_by = request.user
            master_obj.barcode = master_obj.insurance_number
            master_obj.last_update_by = request.user
            master_obj.save()
            patient_attachments = Patient_Files_formset(request.POST, request.FILES, instance=master_obj)
            detail_obj = patient_attachments.save(commit=False)
            for x in detail_obj:
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
            past_med_obj = patient_past_med.save(commit=False)
            past_med_obj.patient = master_obj
            past_med_obj.created_by = request.user
            past_med_obj.last_update_by = request.user
            past_med_obj.save()
            messages.success(request, 'تم الحفظ بنجاح')
            return redirect('patient:view-patient', pk=master_obj.id)
        else:
            print(patient_form.errors)
            messages.error(request, patient_form.errors)
            messages.error(request, patient_past_med.errors)
            for error in patient_attachments.errors:
                messages.error(request, error)
    createContext = {
                     'page_title':_('EDIT PATIENT {}').format(required_patient),
                     'patient_form':patient_form,
                     'patient_past_med':patient_past_med,
                     'patient_id':pk,
                     'patient_attachments':patient_attachments,
    }
    return render(request, 'create-patient.html', createContext)

@login_required(login_url='/login')
def delete_patient(request, pk):
    required_patient = get_object_or_404(Patient, pk=pk)
    required_patient.delete()
    return redirect('patient:all-patients')


@login_required(login_url='/login')
def list_gyno_view(request):
    all_gyno = Gynecology.objects.all()
    gyno_formset = GynecologyForm()
    if request.method == 'POST':
        gyno_formset = GynecologyForm(request.POST)
        if gyno_formset.is_valid():
            gyno_obj = gyno_formset.save(commit=False)
            # for x in gyno_obj:
            gyno_obj.created_by = request.user
            gyno_obj.last_update_by = request.user
            gyno_obj.save()
            return redirect("patient:all-gynos")
        else:
            print(gyno_formset.errors)
    gyno_context={
             'page_title':_('GYN LIST'),
             'page_title_gyno':_('GYN DIAGNOSIS'),
             'all_gyno':all_gyno,
             'gyno_form':gyno_formset,
             }
    return render(request, 'gyno/list-gyno.html', gyno_context)

@login_required(login_url='/login')
def create_gyno_view(request):
    gyno_formset = GynecologyForm()
    # gyno_formset = Gynecology_formset(queryset = Gynecology.objects.none())
    if request.method == 'POST':
        gyno_formset = GynecologyForm(request.POST)
        if gyno_formset.is_valid():
            gyno_obj = gyno_formset.save(commit=False)
            # for x in gyno_obj:
            gyno_obj.created_by = request.user
            gyno_obj.last_update_by = request.user
            gyno_obj.save()

patient/templates/diabetes.html
{% extends 'master.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}

{% block body %}

<div class="container-fluid">
  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">{{ page_title|title }}</h5>
    </div>
  </div>
  <!-- /Title -->

  <!-- Row -->
  <form id="my_form" method="POST"class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row" style="padding-bottom: 10px;">
      <div class="pull-right">
        <button type="submit" class="btn btn-success btn-anim">
          <i class="fa fa-arrow-circle-left"></i><span class="btn-text">{% trans "Save" %}</span>
        </button>
        <a href="{% url 'patient:view-patient' pk=required_patient.id %}" class="btn btn-default btn-anim">
          <i class="fa fa-arrow-circle-left"></i><span class="btn-text">{% trans "Back to patient" %}</span>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark"></h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <div class="form-wrap">
                <div class="form-group mb-0">
                  <div class="col-sm-12">
                    <div class="row">
                      <div class="col-sm-4">
                        <label class="control-label mb-10">{{ diabete_form.bs.label }}</label>
                        {{ diabete_form.bs}}
                      </div>
                      <div class="col-sm-4">
                        <label class="control-label mb-10">{{ diabete_form.bp_up.label }}</label>
                        {{ diabete_form.bp_up}}
                      </div>
                      <div class="col-sm-4">
                        <label class="control-label mb-10">{{ diabete_form.bp_down.label }}</label>
                        {{ diabete_form.bp_down}}
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-sm-4">
                        <label class="control-label mb-10">{{ diabete_form.temp.label }}</label>
                        {{ diabete_form.temp}}
                      </div>
                      <div class="col-sm-4">
                        <label class="control-label mb-10">{{ diabete_form.reading_date.label }}</label>
                        {{ diabete_form.reading_date}}
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </form>
  <!-- /Row -->
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default card-view">
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="table-wrap">
              <div class="table-responsive">
                <div id="datable_1_wrapper" class="dataTables_wrapper">
                  <table id="listPatientsTbl" class="table table-hover display  pb-30 dataTable">
                    <thead>
                      <tr role="row">
                        <th style="text-align:center;">{% trans '#' %}</th>
                        <th style="text-align:center;">{% trans 'Reading date' %}</th>
                        <th style="text-align:center;">{% trans 'Blood Sugar' %}</th>
                        <th style="text-align:center;">{% trans 'Blood pressure up' %}</th>
                        <th style="text-align:center;">{% trans 'Blood pressure down' %}</th>
                        <th style="text-align:center;">{% trans 'Temperature' %}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for check in list_diabetes %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{check.reading_date}}</td>
                        <td>{{check.bs}}</td>
                        <td>{{check.bp_up}}</td>
                        <td>{{check.bp_down}}</td>
                        <td>{{check.temp}}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <canvas id="patients-diabetes-chart" data-url="{% url 'patient:patients-diabetes-chart' patient_id=required_patient.id %}"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>
<!--  -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
  $(function() {
    var $populationChart = $("#patients-diabetes-chart");
    $.ajax({
      url: $populationChart.data("url"),
      success: function(data) {

        var ctx = $populationChart[0].getContext("2d");

        new Chart(ctx, {
          type: 'line',
          data: {
            labels: data.labels,
            datasets: [{
              label: 'سكر المريضة',
              backgroundColor: 'red',
              borderColor: 'red',
              data: data.bs,
              fill:false,
            },{
              label: 'SBP',
              backgroundColor: 'blue',
              borderColor: 'blue',
              data: data.bp_up,
              fill:false,
            },{
              label: 'DBP',
              backgroundColor: 'orange',
              borderColor: 'orange',
              data: data.bp_down,
              fill:false,
            }
          ],
          },
          options: {
            responsive: true,
            scales: {
					xAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Month'
						}
					}],
					yAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Value'
						}
					}]
				},
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'رسم بياني للمتابعة الدورية للمريضة'
            }
         }
        });
      }
    });
  });
</script>
{% endblock body %}

patient/templates/list-patients.html
{% extends 'master.html'%}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block body %}
<div class="container-fluid">

  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">{{ page_title }}</h5>
    </div>

  </div>
  <!-- /Title -->

  <!-- Row -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <form action="{% url 'patient:search-barcode' %}" method="post">
              {% csrf_token %}
              <div class="col-md-12">
                <input type="text" class="form-control" name="barcode" id="barcode" placeholder="Barcode Search ...">
              </div>
            </form>
          </div>
          <div class="pull-right">
            <a href="{% url 'patient:create-patient' %}" class="btn btn-primary btn-anim">
              <i class="fa fa-wpforms"></i>
              <span class="btn-text">{% trans 'Add New Patient' %}</span>
            </a>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="table-wrap">
              <div class="table-responsive">
                <div id="datable_1_wrapper" class="dataTables_wrapper">
                  <table id="listPatientsTbl" class="table table-hover display  pb-30 dataTable">
                    <thead>
                      <tr role="row">
                        <th>{% trans 'Patient Name' %}</th>
                        <th>{% trans 'Insurance number' %}</th>
                        <th>{% trans 'Patient number' %}</th>
                        <th>{% trans 'date of birth' %}</th>
                        <th>{% trans 'Type' %}</th>
                        <th>{% trans 'Barcode Print' %}</th>
                        <th>{% trans 'Actions' %}</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>{% trans 'Patient Name' %}</th>
                        <th>{% trans 'Insurance number' %}</th>
                        <th>{% trans 'Patient number' %}</th>
                        <th>{% trans 'date of birth' %}</th>
                        <th>{% trans 'Type' %}</th>
                        <th>{% trans 'Barcode Print' %}</th>
                        <th>{% trans 'Actions' %}</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for patient in all_patients %}
                      <tr>
                        <td><a href="{% url 'patient:view-patient' pk=patient.id %}">{{patient.name}}</a></td>
                        <td>{{patient.insurance_number}}</td>
                        <td>{{patient.patient_number}}</td>
                        <td>{{patient.date_of_birth}}</td>
                        <td style="">
                          {% if patient.patient_type == 'CHECK_UP' %}
                          متابعة
                          {% elif patient.patient_type == 'CONSULTANT' %}
                          أستشاري
                          {% elif patient.patient_type == 'OPERATION' %}
                          عمليات
                          {% elif patient.patient_type == 'DELIVER' %}
                          ولادة
                          {% else %}
                          --
                          {% endif %}
                        </td>
                        <td>
                          {% if patient.barcode_image %}
                          <iframe src="/media/{{patient.barcode_image}}" id="barcodeImage" width="25px" height="20px" style="display:none;"></iframe>
                          <button type="button" name="button" onclick="printImage()">{% trans 'Print' %}</button>
                          {% endif %}
                        </td>
                        <td class="text-nowrap">
                          <a href="#" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{patient.pk}}" title="{% trans 'Delete' %}">
                            <i class="fa fa-trash-o" style="font-size:20px;color:red"></i>
                          </a>
                        </td>
                      </tr>
                      <div class="modal fade" id="delete-modal{{patient.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-body">
                              <p>{% trans "Are you sure you want to delete this diagnosis ?" %}</p>
                            </div>
                            <div class="modal-footer">
                              <a href="{% url 'patient:delete-patient' pk=patient.id %}" class="btn btn-outline-danger" type="button" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}"><i class="fa fa-trash-o"
                                  style="font-size:20px;color:red"></i></a>
                              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Cancel' %}">&#x2718</button>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Row -->
  <div class="modal fade in" id="barcode-modal" tabindex="-1" role="dialog" aria-labelledby="barcode-modal" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <form action="{% url 'patient:search-barcode' %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <label class="control-label mb-10" for="username">{% trans 'Enter Barcode' %}</label>
                <input type="text" class="form-control" name="barcode" id="barcode" placeholder="Barcode Search ...">
              </div>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Cancel' %}</button>

              <button type="submit" name="button" class="btn btn-danger">{% trans 'Search' %}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock body %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#listPatientsTbl').DataTable();
  });
</script>

<script type="text/javascript">
  function printImage() {
    var iframe = document.getElementById('barcodeImage')
    iframe.contentWindow.print()
  }
</script>
{% endblock js %}

patient/templates/top-button.html
{% load i18n %}
{% load l10n %}
{% load static %}

<div class="btn-group">
	<div class="dropdown">
		<!-- Single button -->
		<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		{% trans 'Patient Pages' %}
		<span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
		<li><a href="{% url 'patient:create-days-off' patient_id=patient_id  %}">{% trans 'Patient Days off' %}</a></li>
		<li><a href="{% url 'surgery:create-patient-surgery' patient_id=patient_id  %}">{% trans 'Patient surgery' %}</a></li>
		<li><a href="{% url 'patient:all-delivery' pk=patient_id %}">{% trans 'Patient delivery' %}</a></li>
    <li><a href="{% url 'patient:all-checkup' patient_id=patient_id %}">{% trans 'Patient Follow-ups' %}</a></li>
    <li><a href="{% url 'patient:create-diabetes' patient_id=patient_id %}">{% trans 'Patient Diabetes & BP' %}</a></li>
		<li><a href="#" data-toggle="modal" data-target="#exampleModal">{% trans 'Patient Exits' %}</a></li>
		</ul>
	</div>
</div>
<div class="btn-group">
	<div class="dropdown">
		<!-- Single button -->
		<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		{% trans 'Actions' %}
		<span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
		<li><a href="{% url 'patient:update-patient' pk=patient_id %}">{% trans 'Update & Edit' %}</a></li>
		<li><a href="{% url 'patient:all-patients' %}">{% trans 'Cancel & Back' %}</a></li>
		</ul>
	</div>
</div>