home/urls.py
from django.urls import path, include
from home import views
from report.views import list_all_patients_view


app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('add-user/', views.addUserView, name='new-user'),
        path('register/', views.register, name='register'),
        path('', views.homepage, name='homepage'),
        path('', list_all_patients_view, name='rep-all-patients'),
]

patient/urls.py
from django.urls import path
from patient import views

app_name = 'patient'

urlpatterns =[
    path('patient/list/', views.list_patients_view, name='all-patients'),
    path('patient/create/', views.create_patient_view, name='create-patient'),
    path('patient/view/<int:pk>', views.view_patient_view, name='view-patient'),
    path('patient/update/<int:pk>', views.update_patient_view, name='update-patient'),
    path('patient/delete/<int:pk>', views.delete_patient, name='delete-patient'),
    path('gyno/list/', views.list_gyno_view, name='all-gynos'),
    path('gyno/create/', views.create_gyno_view, name='create-gyno'),
    path('gyno/update/<int:pk>', views.update_gyno_view, name='update-gyno'),
    path('gyno/delete/<int:pk>', views.delete_gyno_view, name='delete-gyno'),
    path('delivery/create/list/<int:pk>', views.create_delivery_view, name='all-delivery'),
    path('delivery/update/list/<int:pk>/<int:patient_id>', views.update_delivery_view, name='update-delivery'),
    path('checkup/create/list/<int:patient_id>', views.create_list_check_up_view, name='all-checkup'),
    path('us/create/<int:check_id>/<int:patient_id>/', views.ultrasound_create_view, name='create-us'),
    path('checkup/view/<int:patient_id>/<int:chk_id>', views.view_list_check_up_view, name='view-checkup'),
    path('checkup/update/<int:patient_id>/<int:chk_id>', views.update_patient_medicine_view, name='update-checkup'),
    path('medicine/create/<int:patient_id>/<int:chk_id>', views.create_patient_medicine_view, name='create-med'),
    path('cons/list/', views.list_patient_consultant_view, name='all-con-patients'),
    path('create/days-off/<int:patient_id>', views.create_patient_days_off_view, name='create-days-off'),
    path('create/diabete/<int:patient_id>', views.create_diabetes_view, name='create-diabetes'),
    path('chart/diabete/<int:patient_id>', views.patient_diabete_chart, name='patients-diabetes-chart'),


    path('search/barcode/', views.view_patient_barcode, name='search-barcode'),
]

report/urls.py
from django.urls import path
from report import views

app_name = 'report'

urlpatterns =[
          path('patient/api/', views.report_dashboard_view, name='rep-dashboard'),
          path('patient/details/api/', views.total_patients_details_view, name='total-patients-details'),
          path('all/patients/report/', views.list_all_patients_view, name='rep-all-patients'),
          path('cons/patients/report/', views.list_consultant_patients_view, name='rep-cons-patients'),
          path('clexane/patients/report/', views.list_clexane_patients_view, name='rep-clexane-patients'),
          path('view/patient/report/<int:patient_id>', views.view_patient_history_view, name='patient-report'),
          path('view/patient/checkup/<int:checkup_id>', views.patient_checkup_report_view, name='patient_check_up_report'),
          path('patients/entrance/chart/', views.patients_entrance_chart, name='patients-entrance-chart'),
          path('delivery/type/chart/', views.delivery_type_chart, name='delivery-type-chart'),
          path('surgery/type/chart/', views.surgery_type_chart, name='surgery-type-chart'),
]

womanClinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
            path('i18n/', include('django.conf.urls.i18n')),
            path('admin/', admin.site.urls),
            path('', include('home.urls'), name='home'),
            path('patients/', include('patient.urls'), name='patient'),
            path('medicine/', include('pharmacy.urls'), name='pharmacy'),
            path('surgery/', include('surgery.urls'), name='surgery'),
            path('report/', include('report.urls'), name='reports'),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#             path('admin/', admin.site.urls),
#             path('', include('home.urls'), name='home'),
#             path('patients/', include('patient.urls'), name='patient'),
#             path('medicine/', include('pharmacy.urls'), name='pharmacy'),
#             path('surgery/', include('surgery.urls'), name='surgery'),
#             path('report/', include('report.urls'), name='reports'),
# )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/models.py
from django.db import models

# Create your models here.

report/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from datetime import date
from django.db.models import Count
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from patient.models import (Patient, Delivery, Check_Up, Gynecology,Past_Medical_History,
                            Patient_Medicine, Patient_Days_Off,Ultrasound, Diabetes )
from surgery.models import Patient_Surgery
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions


@login_required(login_url='/login')
def report_dashboard_view(request):
    patient_count = Patient.objects.all().count()
    patient_exit_chart = Patient.objects.filter(exit_date__isnull=False)
    patients_consult_count = Patient.objects.filter(transferred_from__isnull = False).count()
    patients_clexane_count = Patient.objects.filter(clexane_order_number__isnull = False).count()
    labels = []
    chart_data = []
    for x in patient_exit_chart.values('exit_date').annotate(num_of_exit_patient = Count('exit_date')):
        labels.append(x['exit_date'].month)
        chart_data.append(x['num_of_exit_patient'])
    repContext={
                'page_title':'شاشة التقارير الرئيسية',
                'patient_count':patient_count,
                'patients_consult_count':patients_consult_count,
                'patients_clexane_count':patients_clexane_count,
                'patient_exit_chart':patient_exit_chart,
                "labels":labels,
                "chart_data":chart_data,
    }
    return render(request, 'report-dashboard.html', repContext)

@login_required(login_url='/login')
def list_all_patients_view(request):
    all_patients = Patient.objects.all()
    context={'page_title':'شاشة تقارير كافة المريضات',
             'all_patients':all_patients
             }
    return render(request, 'list-all-patients-report.html', context=context)

@login_required(login_url='/login')
def view_patient_history_view(request, patient_id):
    # patient info
    required_patient = get_object_or_404(Patient, id = patient_id)
    patient_past_medical_history = Past_Medical_History.objects.filter(patient= patient_id).first()
    # patient deliveries
    patient_delivery = Delivery.objects.filter(patient = patient_id)
    # patient check up
    patient_check_ups = Check_Up.objects.filter(patient = patient_id)
    # patient medicine
    patient_medicine = Patient_Medicine.objects.filter(check_up__in = patient_check_ups)
    # patient ultrasound
    patient_us = Ultrasound.objects.filter(check_up__patient = patient_id)
    # patient delivery
    patient_days_off = Patient_Days_Off.objects.filter(patient = patient_id)
    # patient surgeries
    patient_surgery = Patient_Surgery.objects.filter(patient = patient_id)
    # patient diabetes
    patient_diabete = Diabetes.objects.filter(patient = patient_id)

    context={'page_title':'تقرير عام عن المريضة  {}'.format(required_patient),
             'required_patient':required_patient,
             'patient_past_medical_history':patient_past_medical_history,
             'patient_delivery':patient_delivery,
             'patient_check_ups':patient_check_ups,
             'patient_medicine':patient_medicine,
             'patient_us':patient_us,
             'patient_days_off':patient_days_off,
             'patient_surgery':patient_surgery,
             'patient_diabete':patient_diabete,
             }
    return render(request, 'patient-history-report.html', context=context)

@login_required(login_url='/login')
def list_consultant_patients_view(request):
    all_patients = Patient.objects.filter(transferred_from__isnull = False)
    context={'page_title':'عرض المريضات',
             'all_patients':all_patients
             }
    return render(request, 'list-cons-patients-report.html', context=context)

@login_required(login_url='/login')
def list_clexane_patients_view(request):
    all_patients = Patient.objects.filter(clexane_order_number__isnull = False)
    context={'page_title':'مريضات الكلكسان',
             'all_patients':all_patients
             }
    return render(request, 'list-clexane-patients-report.html', context=context)

@login_required(login_url='/login')
def total_patients_details_view(request):
    all_patients = Patient.objects.filter(transferred_from__isnull = False)
    context={'page_title':'احصائيات عن اجمالي المريضات',
             'all_patients':all_patients
             }
    return render(request, 'total-patients-details.html', context=context)

@login_required(login_url='/login')
def list_surgery_patients_view(request):
    surgery_patients = Patient_Surgery.objects.all()
    context={'page_title':'مريضات العمليات',
             'surgery_patients':surgery_patients
             }
    return render(request, 'list-patients.html', context=context)

@login_required(login_url='/login')
def list_surgery_patients_view(request):
    days_off_patients = Patient_Days_Off.objects.all()
    context={'page_title':'اجازات المرضي',
             'days_off_patients':days_off_patients
             }
    return render(request, 'list-patients.html', context=context)

@login_required(login_url='/login')
def patient_checkup_report_view(request, checkup_id):
    required_checkup = get_object_or_404(Check_Up, id=checkup_id)
    context={'page_title':'تقرير متابعة الاسبوع رقم {0} للمريضة {1} '.format(required_checkup.week_number, required_checkup.patient.name),
             'required_checkup':required_checkup,
             'patient_id':required_checkup.patient
             }
    return render(request, 'checkup-report.html', context)

@login_required(login_url='/login')
def patients_entrance_chart(request):
    labels = []
    qs1 = []
    qs2 = [0]

    queryset = Patient.objects.values('entrance_date').annotate(num_of_entrance_patient = Count('entrance_date'))
    queryset2 = Patient.objects.values('exit_date').annotate(num_of_exit_patient = Count('exit_date'))
    for entry in queryset:
        labels.append(entry['entrance_date'])
        qs1.append(entry['num_of_entrance_patient'])
    for exit in queryset2:
        qs2.append(exit['num_of_exit_patient'])
    return JsonResponse(data={
        'labels': labels,
        'qs1': qs1,
        'qs2': qs2,
    })

@login_required(login_url='/login')
def delivery_type_chart(request):
    labels = []
    ds_type = []
    queryset = Delivery.objects.values('type').annotate(Count('type'))
    for delivery in queryset:
        if delivery['type'] == 'c':
            labels.append('قيصري')
        else:
            labels.append('طبيغي')
        ds_type.append(delivery['type__count'])
    return JsonResponse(data={
        'labels': labels,
        'ds_type': ds_type
    })


@login_required(login_url='/login')
def surgery_type_chart(request):
    labels = []
    ds_type = []
    queryset = Patient_Surgery.objects.values('surgery_name__surgery_name').annotate(Count('surgery_name'))
    for surgery in queryset:
        labels.append(surgery['surgery_name__surgery_name'])
        ds_type.append(surgery['surgery_name__count'])
    return JsonResponse(data={
        'labels': labels,
        'ds_type': ds_type
    })

report/templates/all-patients.html
{% extends 'master.html' %}
{% load static %}

{% block body %}
<div class="container-fluid">

  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">All Patients</h5>
    </div>
    
  </div>
  <!-- /Title -->

  <!-- Row -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark">Patients List</h6>
          </div>
          <div class="pull-right">
            <a href="{% url 'patient:create-patient' %}" class="btn btn-primary btn-anim">
              <i class="fa fa-wpforms"></i>
              <span class="btn-text">Add New Patient</span>
            </a>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="table-wrap">
              <div class="table-responsive">
                <div id="datable_1_wrapper" class="dataTables_wrapper">
                  <table id="listPatientsTbl" class="table table-hover display  pb-30 dataTable">
                    <thead>
                      <tr role="row">
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Mobile</th>
                        <th>Date Of Birth</th>
                        <th>Husband Name</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Mobile</th>
                        <th>Date Of Birth</th>
                        <th>Husband Name</th>
                        <th>Actions</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for patient in patients_list %}
                      <tr>
                        <td>{{patient.name}}</td>
                        <td>{{patient.phone}}</td>
                        <td>{{patient.mobile}}</td>
                        <td>{{patient.date_of_birth}}</td>
                        <td>{{patient.husband_name}}</td>
                        <td class="text-nowrap">
                          <a href="#" class="mr-25" data-toggle="tooltip" data-original-title="Edit">
                            <i class="fa fa-pencil text-inverse m-r-10"></i>
                          </a>
                          <a href="#" data-toggle="tooltip" data-original-title="Close">
                              <i class="fa fa-close text-danger"></i>
                          </a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Row -->

</div>
{% endblock body %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#listPatientsTbl').DataTable();
  });
</script>
{% endblock js %}

report/templates/checkup-report.html
{% extends 'master.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}
{% block body %}

<div class="col-xl-12">
  <p>
    <div class="btn-group">
      <a href="{% url 'report:patient-report' patient_id=patient_id.id %}" class="btn btn-success">الرجوع</a>
    </div>
  </p>
  <!-- patiebt info -->
  <div class="card">
    <div class="card-header">{{ page_title }}</div>
    <div class="card-body">
      <div class="row show-grid">
        <div class="col-md-6">
          <strong><label>اسبوع الحمل : </label></strong>
          {{ required_checkup.week_number}}
        </div>
        <div class="col-md-6">
          <strong><label>شكوي المريضة : </label></strong>
          {{ required_checkup.complain}}
        </div>
        <div class="col-md-6">
          <strong><label>تاريخ الزيارة : </label></strong>
          {{ required_checkup.visit_date}}
        </div>
        <div class="col-md-6">
          <strong><label>الزيارة القادمة : </label></strong>
          {{ required_checkup.next_visit}}
        </div>
        <div class="col-md-6">
          <strong><label>ضغط الدم : </label></strong>
          {{ required_checkup.blood_presure}}
        </div>
        <div class="col-md-6">
          <strong><label>بروتين : </label></strong>
          {{ required_checkup.protine}}
        </div>
        <div class="col-md-6">
          <strong><label>RBS : </label></strong>
          {{ required_checkup.rbs}}
        </div>
        <div class="col-md-6">
          <strong><label>Hb% : </label></strong>
          {{ required_checkup.hemoglobin}}
        </div>
        <div class="col-md-6">
          <strong><label>المشيمة : </label></strong>
          {{ required_checkup.placenta}}
        </div>
        <div class="col-md-6">
          <strong><label>نسبة المياه : </label></strong>
          {{ required_checkup.water}}
        </div>
        <div class="col-md-6">
          <strong><label>وضعية الجنين : </label></strong>
          {{ required_checkup.fetal_position}}
        </div>
        <div class="col-md-6">
          <strong><label>حركة الجنين : </label></strong>
          {{ required_checkup.fetal_movement}}
        </div>
        <div class="col-md-6">
          <strong><label>ضربات قلب الجنين : </label></strong>
          {{ required_checkup.fetal_heart_rate}}
        </div>
        <div class="col-md-6">
          <strong><label>وزن الجنين : </label></strong>
          {{ required_checkup.weight}}
        </div>
        <div class="col-md-6">
          <strong><label>طبيعة خروج المريضة : </label></strong>
          {{ required_checkup.exit_nature}}
        </div>
        <div class="col-md-6">
          <strong><label>وصف الخروج : </label></strong>
          {{ required_checkup.exit_desc}}
        </div>
        <div class="col-md-6">
          <strong><label>عمليات جراحية : </label></strong>
          {{ required_checkup.surgery}}
        </div>
        <div class="col-md-6">
          <strong><label>الوصف : </label></strong>
          {{ required_checkup.surgery_desc}}
        </div>
        <div class="col-md-6">
          <strong><label>تاريخ صرف الكلكسان : </label></strong>
          {{ required_checkup.clexane_sarf_date}}
        </div>
        <div class="col-md-6">
        </div>
        <div class="col-md-12">
          <strong><label>mhx : </label></strong>
          {{ required_checkup.mhx}}
        </div>
        <div class="col-md-12">
          <strong><label>shx : </label></strong>
          {{ required_checkup.shx}}
        </div>
        <div class="col-md-12">
          <strong><label>Allergy hx : </label></strong>
          {{ required_checkup.allergy_hx}}
        </div>
        <div class="col-md-12">
          <strong><label>g : </label></strong>
          {{ required_checkup.g}}
        </div>
        <div class="col-md-12">
          <strong><label>p : </label></strong>
          {{ required_checkup.p}}
        </div>
        <div class="col-md-12">
          <strong><label>Pre : </label></strong>
          {{ required_checkup.pre}}
        </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- end of patient info -->

  <!-- /.panel -->
</div>

{% endblock body %}

report/templates/list-all-patients-report.html
{% extends 'master.html'%}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block body %}
<div class="container-fluid">
  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">{{ page_title }}</h5>
    </div>
    
  </div>
  <!-- /Title -->

  <!-- Row -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark">{{ page_title }}</h6>
          </div>
          <div class="pull-right">
            <a href="{% url 'patient:create-patient' %}" class="btn btn-primary btn-anim">
              <i class="fa fa-wpforms"></i>
              <span class="btn-text">{% trans 'Add New Patient' %}</span>
            </a>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="table-wrap">
              <div class="table-responsive">
                <div id="datable_1_wrapper" class="dataTables_wrapper">
                  <table id="listPatientsTbl" class="table table-hover display  pb-30 dataTable">
                    <thead>
                      <tr role="row">
                        <th>{% trans 'Patient name' %}</th>
                        <th>{% trans 'Phone' %}</th>
                        <th>{% trans 'Mobile' %}</th>
                        <th>{% trans 'Date Of Birth' %}</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>{% trans 'Patient name' %}</th>
                        <th>{% trans 'Phone' %}</th>
                        <th>{% trans 'Mobile' %}</th>
                        <th>{% trans 'Date Of Birth' %}</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for patient in all_patients %}
                      <tr>
                        <td><a href="{% url 'report:patient-report' patient_id=patient.id %}">{{patient.name}}</a></td>
                        <td>{{patient.patient_number}}</td>
                        <td>{{patient.insurance_number}}</td>
                        <td>{{patient.date_of_birth}}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Row -->
</div>

{% endblock body %}

{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#listPatientsTbl').DataTable();
  });
</script>
{% endblock js %}

report/templates/report-dashboard.html
{% extends 'master.html'%}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block body %}
<div class="container-fluid pt-25">
  <!-- Row -->
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <div class="panel panel-default card-view pa-0">
        <div class="panel-wrapper collapse in">
          <div class="panel-body pa-0">
            <div class="sm-data-box">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-xs-6 text-center pl-0 pr-0 data-wrap-left">
                    <span class="txt-dark block counter"><span class="counter-anim">{{patient_count}}</span></span>
                    <span class="weight-500 uppercase-font block font-13"><a href="{% url 'report:rep-all-patients' %}">{% trans 'TOTAL PATIENTS' %}</a></span>
                  </div>
                  <div class="col-xs-6 text-center  pl-0 pr-0 data-wrap-right">
                    <i class="icon-user-following data-right-rep-icon txt-light-grey"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <div class="panel panel-default card-view pa-0">
        <div class="panel-wrapper collapse in">
          <div class="panel-body pa-0">
            <div class="sm-data-box">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-xs-6 text-center pl-0 pr-0 data-wrap-left">
                    <span class="txt-dark block counter"><span class="counter-anim">{{patients_consult_count}}</span></span>
                    <span class="weight-500 uppercase-font block">
                      <a href="{% url 'report:rep-cons-patients' %}">{% trans 'CONSULTANT PATIENTS' %}</a></span>
                  </div>
                  <div class="col-xs-6 text-center  pl-0 pr-0 data-wrap-right">
                    <i class="fa fa-female  data-right-rep-icon txt-light-grey"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <div class="panel panel-default card-view pa-0">
        <div class="panel-wrapper collapse in">
          <div class="panel-body pa-0">
            <div class="sm-data-box">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-xs-6 text-center pl-0 pr-0 data-wrap-left">
                    <span class="txt-dark block counter"><span class="counter-anim">{{patients_clexane_count}}</span></span>
                    <span class="weight-500 uppercase-font block"><a href="{% url 'report:rep-clexane-patients'%}">{% trans 'TOTAL CLEXANE PATIENTS' %}</a></span>
                  </div>
                  <div class="col-xs-6 text-center  pl-0 pr-0 data-wrap-right">
                    <i class="fa fa-medkit  data-right-rep-icon txt-light-grey"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Row -->

  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark"></h6>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="flot-container" style="height:400px">
              <div id="sales_bars_chart" class="demo-placeholder" style="padding: 0px; position: relative;">
                <canvas id="patients-entrance-chart" width="767" height="400" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 767px; height: 400px;" data-url="{% url 'report:patients-entrance-chart' %}"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark"></h6>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="flot-container" style="height:400px">
              <div id="sales_bars_chart" class="demo-placeholder" style="padding: 0px; position: relative;">
                <canvas id="delivery-type-chart" width="767" height="400" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 767px; height: 400px;" data-url="{% url 'report:delivery-type-chart' %}"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark"></h6>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="flot-container" style="height:400px">
              <div id="sales_bars_chart" class="demo-placeholder" style="padding: 0px; position: relative;">
                <canvas id="patients-surgery-chart" width="767" height="400" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 767px; height: 400px;" data-url="{% url 'report:surgery-type-chart' %}"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
  $(function() {
    var $populationChart = $("#patients-entrance-chart");
    $.ajax({
      url: $populationChart.data("url"),
      success: function(data) {
        var ctx = $populationChart[0].getContext("2d");
        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: data.labels,
            datasets: [{
              label: 'المريضات',
              backgroundColor: '#428bca',
              data: data.qs1
            }]
          },
          options: {
            responsive: true,
            scales: {
              yAxes: [{
                ticks: {
                  min: .5,
                }
              }]
            },
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'احصائيةعدد المريضات الشهري'
            }
          }
        });

      }
    });

  });
</script>
<!-- *************************************************** -->
<script>
  $(function() {
    var $populationChart = $("#delivery-type-chart");
    $.ajax({
      url: $populationChart.data("url"),
      success: function(data) {
        var ctx = $populationChart[0].getContext("2d");
        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: data.labels,
            datasets: [{
              label: 'انواع الولادات',
              backgroundColor: '#428bca',
              data: data.ds_type
            }]
          },
          options: {
            responsive: true,
            scales: {
              yAxes: [{
                ticks: {
                  min: .5,
                }
              }]
            },
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'عدد مريضات الولادة الطبيعي و القيصري'
            }
          }
        });

      }
    });

  });
</script>
<!-- ************************************************************ -->
<script>
  $(function() {
    var $populationChart = $("#patients-surgery-chart");
    $.ajax({
      url: $populationChart.data("url"),
      success: function(data) {
        var ctx = $populationChart[0].getContext("2d");
        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: data.labels,
            datasets: [{
              label: 'انواع العمليات',
              backgroundColor: '#428bca',
              data: data.ds_type
            }]
          },
          options: {
            responsive: true,
            scales: {
              yAxes: [{
                ticks: {
                  min: .5,
                }
              }]
            },
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'احصائية بالعمليات'
            }
          }
        });

      }
    });

  });
</script>

{% endblock body %}