home/urls.py
from django.urls import path, include
from home import views
from report.views import list_all_patients_view


app_name = 'home'

urlpatterns=[
        path('en/', views.viewEN, name='en'),
        path('ar/', views.viewAR, name='ar'),
        path('login/', views.user_login, name='user-login'),
        path('logout/', views.user_logout, name='logout'),
        path('add-user/', views.addUserView, name='new-user'),
        path('register/', views.register, name='register'),
        path('', views.homepage, name='homepage'),
        path('', list_all_patients_view, name='rep-all-patients'),
]

patient/urls.py
from django.urls import path
from patient import views

app_name = 'patient'

urlpatterns =[
    path('patient/list/', views.list_patients_view, name='all-patients'),
    path('patient/create/', views.create_patient_view, name='create-patient'),
    path('patient/view/<int:pk>', views.view_patient_view, name='view-patient'),
    path('patient/update/<int:pk>', views.update_patient_view, name='update-patient'),
    path('patient/delete/<int:pk>', views.delete_patient, name='delete-patient'),
    path('gyno/list/', views.list_gyno_view, name='all-gynos'),
    path('gyno/create/', views.create_gyno_view, name='create-gyno'),
    path('gyno/update/<int:pk>', views.update_gyno_view, name='update-gyno'),
    path('gyno/delete/<int:pk>', views.delete_gyno_view, name='delete-gyno'),
    path('delivery/create/list/<int:pk>', views.create_delivery_view, name='all-delivery'),
    path('delivery/update/list/<int:pk>/<int:patient_id>', views.update_delivery_view, name='update-delivery'),
    path('checkup/create/list/<int:patient_id>', views.create_list_check_up_view, name='all-checkup'),
    path('us/create/<int:check_id>/<int:patient_id>/', views.ultrasound_create_view, name='create-us'),
    path('checkup/view/<int:patient_id>/<int:chk_id>', views.view_list_check_up_view, name='view-checkup'),
    path('checkup/update/<int:patient_id>/<int:chk_id>', views.update_patient_medicine_view, name='update-checkup'),
    path('medicine/create/<int:patient_id>/<int:chk_id>', views.create_patient_medicine_view, name='create-med'),
    path('cons/list/', views.list_patient_consultant_view, name='all-con-patients'),
    path('create/days-off/<int:patient_id>', views.create_patient_days_off_view, name='create-days-off'),
    path('create/diabete/<int:patient_id>', views.create_diabetes_view, name='create-diabetes'),
    path('chart/diabete/<int:patient_id>', views.patient_diabete_chart, name='patients-diabetes-chart'),


    path('search/barcode/', views.view_patient_barcode, name='search-barcode'),
]

pharmacy/urls.py
from django.urls import path
from pharmacy import views

app_name = 'pharmacy'

urlpatterns =[
    path('list/', views.list_medicines_view, name='all-medicines'),
    path('medicine/create/', views.create_medicine_view, name='create-medicine'),
    path('medicine/update/<int:pk>', views.update_medicine_view, name='update-medicine'),
     path('medicine/delete/<int:pk>', views.delete_medicine_view, name='delete-medicine'),
]

surgery/urls.py
from django.urls import path
from surgery import views

app_name = 'surgery'

urlpatterns =[
              path('list/', views.list_surgery_view, name='list-surgery-types'),
              path('create/', views.create_surgery_view, name='create-surgery'),
              path('update/<int:pk>', views.update_surgery_view, name='update-surgery'),
              path('view/<int:pk>', views.view_surgery_view, name='view-surgery'),
              path('delete/<int:pk>', views.delete_surgery_view, name='delete-surgery'),
              path('create/patient/surgery/<int:patient_id>', views.create_patient_surgery_view, name='create-patient-surgery'),
              path('list/doctors/', views.list_surgery_doctor_view, name='list-surgery-doctors'),
              path('create/doctor/', views.create_surgery_doctor_view, name='create-doctor'),
              path('update/doctor/<int:pk>', views.update_surgery_doctor_view, name='update-doctor'),
              path('delete/doctor/<int:pk>', views.delete_surgery_doctor_view, name='delete-doctor'),
]

womanClinic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
            path('i18n/', include('django.conf.urls.i18n')),
            path('admin/', admin.site.urls),
            path('', include('home.urls'), name='home'),
            path('patients/', include('patient.urls'), name='patient'),
            path('medicine/', include('pharmacy.urls'), name='pharmacy'),
            path('surgery/', include('surgery.urls'), name='surgery'),
            path('report/', include('report.urls'), name='reports'),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += i18n_patterns(
#             path('admin/', admin.site.urls),
#             path('', include('home.urls'), name='home'),
#             path('patients/', include('patient.urls'), name='patient'),
#             path('medicine/', include('pharmacy.urls'), name='pharmacy'),
#             path('surgery/', include('surgery.urls'), name='surgery'),
#             path('report/', include('report.urls'), name='reports'),
# )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

surgery/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import date
from patient.models import Patient
from surgery.forms import (Surgery_Inline, Surgery_Master_Form, Patient_Surgery_Form,
                           Surgery_Doctor_Form, doctor_Inline,After_Surgery_Form)
from surgery.models import Surgery_Master, Surgery_Steps, Patient_Surgery, Surgery_Doctor,After_Surgery
from django.utils.translation import ugettext_lazy as _


@login_required(login_url='/login')
def list_surgery_view(request):
    all_surgery = Surgery_Master.objects.all()
    master_form = Surgery_Master_Form()
    detail_fromset = Surgery_Inline()
    if request.method == 'POST':
        master_form = Surgery_Master_Form(request.POST)
        detail_fromset = Surgery_Inline(request.POST)
        if master_form.is_valid() and detail_fromset.is_valid():
            master_obj = master_form.save(commit=False)
            master_obj.created_by = request.user
            master_obj.last_update_by = request.user
            master_obj.save()
            detail_fromset = Surgery_Inline(
                request.POST, instance=master_obj)
            if detail_fromset.is_valid():
                det_obj = detail_fromset.save(commit=False)
                for obj in det_obj:
                    obj.created_by = request.user
                    obj.last_update_by = request.user
                    obj.save()
                    return redirect('surgery:list-surgery-types')
    surgeryContext = {
                      'page_title':_('قائمة الجراحات'),
                      "page_title_surgery": _('اضافة عملية جديدة'),
                      'all_surgery':all_surgery,
                      'master_form': master_form,
                      'detail_fromset': detail_fromset,
    }
    return render(request, 'list-surgery.html', surgeryContext)


@login_required(login_url='/login')
def create_surgery_view(request):
    master_form = Surgery_Master_Form()
    detail_fromset = Surgery_Inline()
    if request.method == 'POST':
        master_form = Surgery_Master_Form(request.POST)
        detail_fromset = Surgery_Inline(request.POST)
        if master_form.is_valid() and detail_fromset.is_valid():
            master_obj = master_form.save(commit=False)
            master_obj.created_by = request.user
            master_obj.last_update_by = request.user
            master_obj.save()
            detail_fromset = Surgery_Inline(
                request.POST, instance=master_obj)
            if detail_fromset.is_valid():
                det_obj = detail_fromset.save(commit=False)
                for obj in det_obj:
                    obj.created_by = request.user
                    obj.last_update_by = request.user
                    obj.save()
            return redirect('surgery:list-surgery-types')
    surgeryContext = {
        "page_title": 'اضافة عملية جديدة',
        'master_form': master_form,
        'detail_fromset': detail_fromset,
    }
    return render(request, 'create-surgery.html', surgeryContext)


@login_required(login_url='/login')
def update_surgery_view(request, pk):
    required_surgery = get_object_or_404(Surgery_Master, pk=pk)
    surgery_master_form = Surgery_Master_Form(instance=required_surgery)
    surgery_det_form = Surgery_Inline(instance=required_surgery)
    if request.method == 'POST':
        surgery_master_form = Surgery_Master_Form(request.POST,instance=required_surgery)
        surgery_det_form = Surgery_Inline(request.POST,instance=required_surgery)
        if surgery_master_form.is_valid() and surgery_det_form.is_valid():
            surgery_master_form.save()
            surgery_det_obj = surgery_det_form.save(commit=False)
            for obj in surgery_det_obj:
                obj.created_by = request.user
                obj.last_update_by = request.user
                obj.save()
            return redirect('surgery:list-surgery-types')

    surgeryContext = {
        "page_title": 'تعديل بيانات عملية {}'.format(required_surgery),
        'master_form': surgery_master_form,
        'detail_fromset': surgery_det_form
    }
    return render(request, 'create-surgery.html', surgeryContext)


@login_required(login_url='/login')
def delete_surgery_view(request, pk):
    required_surgery = get_object_or_404(Surgery_Master, pk=pk)
    required_surgery.delete()
    return redirect('surgery:list-surgery-types')


@login_required(login_url='/login')
def view_surgery_view(request, pk):
    required_surgery = get_object_or_404(Surgery_Master, pk=pk)
    return render(request, 'view-surgery.html', {'surgery':required_surgery})


@login_required(login_url='/login')
def create_patient_surgery_view(request, patient_id):
    list_patient_surgery = Patient_Surgery.objects.filter(patient=patient_id)
    required_patient = get_object_or_404(Patient, id=patient_id)
    patient_surgery_form = Patient_Surgery_Form()
    if request.method == 'POST':
        patient_surgery_form = Patient_Surgery_Form(request.POST)
        if patient_surgery_form.is_valid():
            master_obj = patient_surgery_form.save(commit=False)
            master_obj.patient = required_patient
            master_obj.created_by = request.user
            master_obj.last_update_by = request.user
            master_obj.save()
            messages.success(request, 'تـــم التسجيل بنجــاح')
        else:
            messages.error(request, patient_surgery_form.errors)
    surgeryPatientContext = {
        "page_title": 'عمليات النسا',
        'patient_id':patient_id,
        'list_patient_surgery': list_patient_surgery,
        'patient_surgery_form': patient_surgery_form,
    }
    return render(request, 'create-patient-surgery.html', surgeryPatientContext)


@login_required(login_url='/login')
def list_surgery_doctor_view(request):
    all_doctors = Surgery_Doctor.objects.all()
    doctor_form = Surgery_Doctor_Form()
    # doctor_form = doctor_Inline(queryset=Surgery_Doctor.objects.none())
    if request.method == 'POST':
        # doctor_form = doctor_Inline(request.POST)
        doctor_form = Surgery_Doctor_Form(request.POST)
        if doctor_form.is_valid():
            master_obj = doctor_form.save(commit=False)
            # for x in master_obj:
            master_obj.hospital = request.user.clinic
            master_obj.created_by = request.user
            master_obj.last_update_by = request.user
            master_obj.save()
            return redirect('surgery:list-surgery-doctors')
            messages.success(request, _('Saved Successfully'))
        else:
            messages.error(request, doctor_form.errors)
    surgeryContext = {
                      'page_title':_('Doctors List'),
                      'all_doctors':all_doctors,
                      'page_title_doctor':_("Add New Doctor"),
                      'doctor_form':doctor_form
    }
    return render(request, 'list-doctors.html', surgeryContext)


@login_required(login_url='/login')
def create_surgery_doctor_view(request):
    doctor_form = doctor_Inline(queryset=Surgery_Doctor.objects.none())
    if request.method == 'POST':
        doctor_form = doctor_Inline(request.POST)
        if doctor_form.is_valid():
            master_obj = doctor_form.save(commit=False)
            for x in master_obj:
                x.hospital = request.user.clinic
                x.created_by = request.user
                x.last_update_by = request.user
                x.save()
            return redirect('surgery:list-surgery-doctors')
            messages.success(request, 'تـــم التسجيل بنجــاح')
        else:
            messages.error(request, doctor_form.errors)
    surgeryContext = {
                      'page_title':'اضافة دكتور جديد',
                      'doctor_form':doctor_form
    }
    return render(request, 'create-doctor.html', surgeryContext)

@login_required(login_url='/login')
def update_surgery_doctor_view(request,pk):
    required_doctor = get_object_or_404(Surgery_Doctor, pk=pk)
    doctor_form = Surgery_Doctor_Form(instance=required_doctor)
    if request.method == 'POST':
        doctor_form = Surgery_Doctor_Form(request.POST , instance=required_doctor)
        if doctor_form.is_valid():
            doctor_obj = doctor_form.save(commit=False)
            doctor_obj.created_by = request.user
            doctor_obj.last_update_by = request.user
            doctor_obj.save()
            return redirect('surgery:list-surgery-doctors')
            messages.success(request, 'تـــم التسجيل بنجــاح')
        else:
            messages.error(request, doctor_form.errors)
    surgeryContext = {
                      'page_title':_('EDIT {}').format(required_doctor.doctor_name),
                      'doctor_form':doctor_form
    }
    return render(request, 'update-doctors.html', surgeryContext)


@login_required(login_url='/login')
def delete_surgery_doctor_view(request, pk):
    required_doctor = get_object_or_404(Surgery_Doctor, pk=pk)
    required_doctor.delete()
    return redirect('surgery:list-surgery-doctors')

def create_after_surgery_view(request, surgery_id_v):
    after_surg_form = After_Surgery_Form()
    all_follow_ups = After_Surgery.objects.filter()
    if request.method == 'POST':
        after_surg_form = After_Surgery_Form(request.POST)
        if after_surg_form.is_valid():
            after_obj = after_surg_form.save(commit=False)
            after_obj.surgery = surgery_id_v
            after_obj.created_by = request.user
            after_obj.last_update_by = request.user
            after_obj.save()
            # return redirect('surgery:list-surgery-doctors')
            messages.success(request, 'تـــم التسجيل بنجــاح')
        else:
            messages.error(request, doctor_form.errors)
    surgeryContext = {
                      'page_title':'تسجيل متابعة مابعد العملية',
                      'after_surg_form':after_surg_form,

surgery/templates/create-after-surgery.html
{% extends 'master.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}
{% block body %}

<div class="col-xl-12">
  <form id="my_form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'message.html' %}
    <p>
      <button type="submit" class="btn btn-success">حفظ</button>
      <a href="{% url 'patient:all-checkup' patient_id=patient_id %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
      <a href="{% url 'patient:all-checkup' patient_id=
       %}" class="btn btn-secondary">{% trans "تسجيل ملاحظات مابعد العملية" %}</a>
    </p>
    <div class="card">
      <div class="card-header">{{ page_title }}</div>
      <div class="card-body">
        <div class="row show-grid">
          <div class="col-md-12">
            {{ after_surg_form.after_surgery_notes|as_crispy_field}}
          </div>
          <div class="col-md-4">
            {{ after_surg_form.after_surgery_recomendations|as_crispy_field}}
          </div>
          <div class="col-md-8">
          </div>
        </div>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.panel -->
  </form>
  <div class="card">
    <div class="card-body">
      <table class="table" id="dataTable">
        <thead style="background-color: #89acbdb3;">
          <tr role="row">
            <th style="text-align:center;">#</th>
            <th style="text-align:center;">تقدم الحالة</th>
            <th style="text-align:center;">التوصيات</th>
            <th style="text-align:center;">التاريخ</th>
          </tr>
        </thead>
        <tbody>
          {% for follow in all_follow_ups %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{follow.after_surgery_notes}}</td>
            <td>{{follow.after_surgery_recomendations}}</td>
            <td>{{follow.follow_up_date}}</td>
          </tr>
          {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock body %}

surgery/templates/create-doctor.html
{% extends 'master.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}

{% block body %}

<div class="container-fluid">
  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">{{ page_title }}</h5>
    </div>
    
  </div>
  <!-- /Title -->

  <!-- Row -->
  <form id="my_form" method="POST"class="form-horizontal">
    {% csrf_token %}
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark"></h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <table class="table" id="dataTable">
                {{ doctor_form.management_form }}
                {% for form in doctor_form %}
                {{ form.id }}
                {% if forloop.first %}
                <thead>
                  <tr>
                    <th>{% trans '#' %}</th>
                    {% for field in form.visible_fields %}
                    <th style="text-align:center;">{{ field.label|capfirst }}</th>
                    {% endfor %}
                  </tr>
                </thead>
                {% endif %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  {% for field in form.visible_fields %}
                  <td>
                    {# exclude the hidden fields in the form #}
                    {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                  </td>
                  {% endfor %}
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pull-right">
      <button type="submit" class="btn btn-success btn-anim">
        <i class="fa fa-arrow-circle-left"></i><span class="btn-text">{% trans "Save" %}</span>
      </button>
      <a href="{% url 'surgery:list-surgery-doctors' %}" class="btn btn-default btn-anim">
        <i class="fa fa-arrow-circle-left"></i><span class="btn-text">{% trans "Back to list" %}</span>
      </a>
    </div>
  </form>
  <!-- /Row -->
</div>


{% endblock body %}

surgery/templates/create-patient-surgery.html
{% extends 'master.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}

{% block body %}

<div class="container-fluid">
  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">{{ page_title|title }}</h5>
    </div>

  </div>
  <!-- /Title -->

  <!-- Row -->
  <form id="my_form" method="POST"class="form-horizontal">
    {% csrf_token %}
    <div class="row" style="padding-bottom: 10px;">
      <div class="pull-right">
        <button type="submit" class="btn btn-success btn-anim">
          <i class="fa fa-arrow-circle-left"></i><span class="btn-text">{% trans "Save" %}</span>
        </button>
        <a href="{% url 'patient:view-patient' pk=patient_id %}" class="btn btn-default btn-anim">
          <i class="fa fa-arrow-circle-left"></i><span class="btn-text">{% trans "Back to patient" %}</span>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark"></h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <div class="form-wrap">
                <div class="form-group mb-0">
                  <div class="col-sm-12">
                    <div class="row">
                      <div class="col-sm-6">
                        <label class="control-label mb-10">{{ patient_surgery_form.surgery_name.label }}</label>
                        {{ patient_surgery_form.surgery_name}}
                      </div>
                      <div class="col-sm-6">
                        <label class="control-label mb-10">{{ patient_surgery_form.surgery_doctor.label }}</label>
                        {{ patient_surgery_form.surgery_doctor}}
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-6">
                        <label class="control-label mb-10">{{ patient_surgery_form.surgery_date.label }}</label>
                        {{ patient_surgery_form.surgery_date}}
                      </div>
                      <div class="col-sm-6">
                        <label class="control-label mb-10">{{ patient_surgery_form.exit_date.label }}</label>
                        {{ patient_surgery_form.exit_date}}
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-6">
                        <label class="control-label mb-10">{{ patient_surgery_form.case_progress.label }}</label>
                        {{ patient_surgery_form.case_progress}}
                      </div>
                      <div class="col-sm-6">
                        <label class="control-label mb-10">{{ patient_surgery_form.final_diagnosis.label }}</label>
                        {{ patient_surgery_form.final_diagnosis}}
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-12">
                        <label class="control-label mb-10">{{ patient_surgery_form.recomendations.label }}</label>
                        {{ patient_surgery_form.recomendations}}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
  <!-- /Row -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default card-view">
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="table-wrap">
              <div class="table-responsive">
                <div id="datable_1_wrapper" class="dataTables_wrapper">
                  <table id="listPatientsTbl" class="table table-hover display  pb-30 dataTable">
                    <thead>
                      <tr role="row">
                        <th style="text-align:center;">{% trans '#' %}</th>
                        <th style="text-align:center;">{% trans 'طبيعة العملية' %}</th>
                        <th style="text-align:center;">{% trans 'اسم الجراح' %}</th>
                        <th style="text-align:center;">{% trans 'تاريخ العملية' %}</th>
                        <th style="text-align:center;">{% trans 'تاريخ الخروج' %}</th>
                        <th style="text-align:center;">{% trans 'تطور الحالة' %}</th>
                        <th style="text-align:center;">{% trans 'التشخيص النهائي' %}</th>
                        <th style="text-align:center;">{% trans 'توصيات' %}</th>
                        <th style="text-align:center;">{% trans 'Action' %}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for patient_surgery in list_patient_surgery %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{patient_surgery.surgery_name}}</td>
                        <td>{{patient_surgery.surgery_doctor}}</td>
                        <td>{{patient_surgery.surgery_date}}</td>
                        <td>{{patient_surgery.exit_date}}</td>
                        <td>{{patient_surgery.case_progress}}</td>
                        <td>{{patient_surgery.final_diagnosis}}</td>
                        <td>{{patient_surgery.recomendations}}</td>
                        <td class="text-nowrap">
                          <a href="#" class="mr-25" data-toggle="tooltip" data-original-title="Edit">
                            <i class="fa fa-pencil text-inverse m-r-10"></i>
                          </a>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

surgery/templates/list-surgery.html
{% extends 'master.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load l10n %}


{% block body %}
<div class="container-fluid">

  <!-- Title -->
  <div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h5 class="txt-dark">{{ page_title|title }}</h5>
    </div>

  </div>
  <!-- /Title -->

  <!-- Row -->
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default card-view">
        <div class="panel-heading">
          <div class="pull-left">
            <h6 class="panel-title txt-dark"></h6>
          </div>
          <div class="pull-right">
            <a href="{% url 'surgery:create-surgery' %}" class="btn btn-primary btn-anim">
              <i class="fa fa-wpforms"></i>
              <span class="btn-text">{% trans 'Add New Surgery' %}</span>
            </a>

          </div>
          <div class="clearfix"></div>
        </div>
        <div class="panel-wrapper collapse in">
          <div class="panel-body">
            <div class="table-wrap">
              <div class="table-responsive">
                <div id="datable_1_wrapper" class="dataTables_wrapper">
                  <table id="listPatientsTbl" class="table table-hover display  pb-30 dataTable">
                    <thead>
                      <tr role="row">
                        <th>{% trans '#' %}</th>
                        <th>{% trans 'Surgery name' %}</th>
                        <th>{% trans 'Action' %}</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>{% trans '#' %}</th>
                        <th>{% trans 'Surgery name' %}</th>
                        <th>{% trans 'Action' %}</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for surgery in all_surgery %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'surgery:view-surgery' surgery.id %}">{{surgery.surgery_name}}</a></td>
                        <td class="text-nowrap">
                          <a href="{% url 'surgery:update-surgery' surgery.id %}" class="mr-25" data-toggle="tooltip" data-original-title="Edit">
                            <i class="fa fa-pencil text-inverse m-r-10"></i>
                          </a>
                          <a type="button" class="btn cur-p btn-outline-danger" data-toggle="modal" data-target="#delete-modal{{surgery.pk}}" title="{% trans 'Delete' %}">
                            <i class="fa fa-trash-o" style="font-size:20px;color:red"></i>
                          </a>
                        </td>
                      </tr>
                      <div class="modal fade" id="delete-modal{{surgery.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-body">
                              <p>{% trans "Are you sure you want to delete this surgery ?" %}</p>

                            </div>
                            <div class="modal-footer">
                              <a href="{% url 'surgery:delete-surgery' pk=surgery.id %}" class="btn btn-outline-danger" type="button" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Delete' %}"><i class="fa fa-trash-o"
                                  style="font-size:20px;color:red"></i></a>
                              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal" data-toggle="tooltip" data-placement="bottom" title="{% trans 'Cancel' %}">&#x2718</button>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Row -->

</div>
{% endblock body %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#listPatientsTbl').DataTable();
  });
</script>
{% endblock js %}

surgery/templates/update-surgery.html
{% extends 'master.html'%}
{% load static %}
{% load i18n %}
{% load l10n %}
{% block body %}

<form id="my_form" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'message.html' %}

  <section class="panel panel-default">
    <div class="panel-body">
      <header class="panel-heading font-bold pull-left">{{ page_title }}</header>
      <div class="doc-buttons pull-right">
        <button type="submit" class="btn btn-s-md btn-success">حفظ</button>
        <a href="{% url 'pharmacy:all-medicines' %}" class="btn btn-s-md btn-default">{% trans "Cancel" %}</a>
      </div>
    </div>
  </section>

        {{medicine_form}}

</form>


{% endblock body %}